server:
  port: 8082
  context:
  servlet:
    context-path: /demo

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: root

#mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.example.demo.entity